-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 20:30:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`taikhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`taikhoan` (
  `TenDangNhap` VARCHAR(30) NOT NULL,
  `MatKhau` VARCHAR(15) NOT NULL,
  `Quyen` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`TenDangNhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`khachsan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`khachsan` (
  `MaKS` INT(11) NOT NULL AUTO_INCREMENT,
  `TenKS` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `SoSao` INT(11) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `AnhKS` VARCHAR(1000) NULL DEFAULT NULL,
  `TenDangNhap` VARCHAR(30) NULL DEFAULT NULL,
  `TienIch` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaKS`),
  INDEX `fk_taikhoan` (`TenDangNhap` ASC) VISIBLE,
  CONSTRAINT `fk_taikhoan`
    FOREIGN KEY (`TenDangNhap`)
    REFERENCES `hotel`.`taikhoan` (`TenDangNhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`anhks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`anhks` (
  `idanhks` INT(11) NOT NULL AUTO_INCREMENT,
  `linkanh` VARCHAR(200) NULL DEFAULT NULL,
  `MaKS` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idanhks`),
  INDEX `fk_anhks_idx` (`MaKS` ASC) VISIBLE,
  CONSTRAINT `fk_anhks`
    FOREIGN KEY (`MaKS`)
    REFERENCES `hotel`.`khachsan` (`MaKS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`giuong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`giuong` (
  `MaGiuong` INT(11) NOT NULL AUTO_INCREMENT,
  `TenGiuong` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`MaGiuong`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`loaiphong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`loaiphong` (
  `MaLoaiPH` INT(11) NOT NULL AUTO_INCREMENT,
  `TenLoaiPH` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaLoaiPH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`phong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`phong` (
  `MaPH` INT(11) NOT NULL AUTO_INCREMENT,
  `TenPH` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `MaKS` INT(11) NOT NULL,
  `MaGiuong` INT(11) NOT NULL,
  `MaLoaiPH` INT(11) NOT NULL,
  `DienTich` FLOAT NULL DEFAULT NULL,
  `Gia` INT(11) NULL DEFAULT NULL,
  `SoLuongNguoi` INT(11) NULL DEFAULT NULL,
  `SoLuongPH` INT(11) NULL DEFAULT NULL,
  `TinhTrang` INT(11) NULL DEFAULT NULL,
  `GhiChu` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`MaPH`),
  INDEX `fk_giuong_idx` (`MaGiuong` ASC) VISIBLE,
  INDEX `fk_loaiph_idx` (`MaLoaiPH` ASC) VISIBLE,
  INDEX `fk_phks_idx` (`MaKS` ASC) VISIBLE,
  CONSTRAINT `fk_giuong`
    FOREIGN KEY (`MaGiuong`)
    REFERENCES `hotel`.`giuong` (`MaGiuong`),
  CONSTRAINT `fk_loaiph`
    FOREIGN KEY (`MaLoaiPH`)
    REFERENCES `hotel`.`loaiphong` (`MaLoaiPH`),
  CONSTRAINT `fk_phks`
    FOREIGN KEY (`MaKS`)
    REFERENCES `hotel`.`khachsan` (`MaKS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`anhphong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`anhphong` (
  `idanhphong` INT(11) NOT NULL AUTO_INCREMENT,
  `linkanh` VARCHAR(200) NULL DEFAULT NULL,
  `MaPH` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idanhphong`),
  INDEX `fk_anhphong_idx` (`MaPH` ASC) VISIBLE,
  CONSTRAINT `fk_anhphong`
    FOREIGN KEY (`MaPH`)
    REFERENCES `hotel`.`phong` (`MaPH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`nguoidung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`nguoidung` (
  `idNguoiDung` INT(11) NOT NULL AUTO_INCREMENT,
  `Ten` VARCHAR(35) CHARACTER SET 'utf8' NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `SDT` VARCHAR(10) NOT NULL,
  `TenDangNhap` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idNguoiDung`),
  INDEX `fk_nguoidung` (`TenDangNhap` ASC) VISIBLE,
  CONSTRAINT `fk_nguoidung`
    FOREIGN KEY (`TenDangNhap`)
    REFERENCES `hotel`.`taikhoan` (`TenDangNhap`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`datphong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`datphong` (
  `MaDatPH` INT(11) NOT NULL AUTO_INCREMENT,
  `MaPH` INT(11) NOT NULL,
  `idNguoiDung` INT(11) NULL DEFAULT NULL,
  `TenChuPH` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `ThoiGianDat` DATETIME NULL DEFAULT NULL,
  `ThoiGianDen` DATE NULL DEFAULT NULL,
  `ThoiGianDi` DATE NOT NULL,
  `SoLuongDat` INT(11) NOT NULL,
  `GhiChu` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `TinhTrangDat` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MaDatPH`, `MaPH`),
  INDEX `fk_id_nguoidung_idx` (`idNguoiDung` ASC) VISIBLE,
  INDEX `fk_Maph_Phong_idx` (`MaPH` ASC) VISIBLE,
  CONSTRAINT `fk_Maph_Phong`
    FOREIGN KEY (`MaPH`)
    REFERENCES `hotel`.`phong` (`MaPH`),
  CONSTRAINT `fk_id_nguoidung`
    FOREIGN KEY (`idNguoiDung`)
    REFERENCES `hotel`.`nguoidung` (`idNguoiDung`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`tienich`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`tienich` (
  `MaTienIch` INT(11) NOT NULL AUTO_INCREMENT,
  `TenTienIch` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`MaTienIch`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`tienichks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`tienichks` (
  `MaTienIch` INT(11) NOT NULL,
  `MaKS` INT(11) NOT NULL,
  PRIMARY KEY (`MaTienIch`, `MaKS`),
  INDEX `fk_tienichks_idx` (`MaKS` ASC) VISIBLE,
  CONSTRAINT `fk_kstienich`
    FOREIGN KEY (`MaTienIch`)
    REFERENCES `hotel`.`tienich` (`MaTienIch`),
  CONSTRAINT `fk_tienichks`
    FOREIGN KEY (`MaKS`)
    REFERENCES `hotel`.`khachsan` (`MaKS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `hotel`.`tienichphong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`tienichphong` (
  `MaTienIch` INT(11) NOT NULL,
  `MaPH` INT(11) NOT NULL,
  PRIMARY KEY (`MaTienIch`, `MaPH`),
  INDEX `fk_tientichphong_idx` (`MaPH` ASC) VISIBLE,
  CONSTRAINT `fk_tienich`
    FOREIGN KEY (`MaTienIch`)
    REFERENCES `hotel`.`tienich` (`MaTienIch`),
  CONSTRAINT `fk_tientichphong`
    FOREIGN KEY (`MaPH`)
    REFERENCES `hotel`.`phong` (`MaPH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
